target("ppl")
    set_kind("static")
    add_files("host/*.cpp")
    add_includedirs("$(projectdir)/include")
    add_packages("glm")

target("ppl-vulkan")
    set_kind("static")
    add_files("vulkan/*.cpp")
    add_includedirs("$(projectdir)/include")
    add_packages("glm", "spdlog", "volk", "vulkan-memory-allocator", "spirv-reflect")
target_end()
