target("ppl")
    set_kind("static")
    add_files("host/*.cpp")
    add_includedirs("$(projectdir)/include")
    add_packages("glm")

target("ppl-vulkan")
    -- set_kind("static")
    -- add_files("vulkan/*.cpp")
    set_kind("headeronly")
    add_includedirs("$(projectdir)/include")
    add_packages("glm", "volk")
    -- add_deps("ppl")
target_end()