target("ppl")
    set_kind("static")
    add_files("host/*.cpp")
    add_includedirs("$(projectdir)/include")
    add_packages("glm")

target("ppl-vulkan")
    set_kind("static")
    add_files("vulkan/*.cpp")
    add_headerfiles("$(projectdir)/include/vulkan/*.hpp")
    add_includedirs("$(projectdir)/include")
    add_packages("glm", "volk", "vulkan-memory-allocator", "spdlog")
target_end()
