#version 450

#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require

layout(local_size_x = 256) in;

layout(push_constant) uniform PushConstantBlock {
  uint8_t a;
  uint8_t b;
  uint8_t c;
  uint8_t d;
  uint8_t e;
  uint8_t f;
  uint8_t g;
  uint8_t h;
}
pc;

layout(set = 0, binding = 0) buffer InputBuffer { uint8_t u_in_data[]; };
layout(set = 0, binding = 1) buffer OutputBuffer { uint8_t u_out_data[]; };

void main() {
  uint tid = gl_GlobalInvocationID.x;
  // this shader just print all the push constants
  u_out_data[tid] = pc.a;
  u_out_data[tid + 1] = pc.b;
  u_out_data[tid + 2] = pc.c;
  u_out_data[tid + 3] = pc.d;
  u_out_data[tid + 4] = pc.e;
  u_out_data[tid + 5] = pc.f;
  u_out_data[tid + 6] = pc.g;
  u_out_data[tid + 7] = pc.h;
}
